version: "3"

services: 
  www:
    build: .
    restart: always
    ports: 
      - '3009:80'
    volumes:
      - ./www:/var/www/html
    networks: 
      - default
  db:
    image: mariadb
    restart: always
    ports: 
      - '3306:3306'
    environment: 
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 12345
    volumes: 
      - db_data:/var/lib/mariadb
    networks: 
      - default
    
volumes: 
  db_data: